//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESgk.WorkIn.SgkService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ConfigurationName="SgkService.WS_SgkIseGiris")]
    public interface WS_SgkIseGiris {
        
        // CODEGEN: Parameter 'iseGirisKaydetReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisKaydet", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/iseGirisKaydetRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="iseGirisKaydetReturn")]
        ESgk.WorkIn.SgkService.iseGirisKaydetResponse iseGirisKaydet(ESgk.WorkIn.SgkService.iseGirisKaydetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisKaydet", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/iseGirisKaydetRes" +
            "ponse")]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisKaydetResponse> iseGirisKaydetAsync(ESgk.WorkIn.SgkService.iseGirisKaydetRequest request);
        
        // CODEGEN: Parameter 'tckimlikNoTarihileiseGirisSorgulaReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileiseGirisSorgula", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/tckimlikNoTarihil" +
            "eiseGirisSorgulaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tckimlikNoTarihileiseGirisSorgulaReturn")]
        ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse tckimlikNoTarihileiseGirisSorgula(ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoTarihileiseGirisSorgula", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/tckimlikNoTarihil" +
            "eiseGirisSorgulaResponse")]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse> tckimlikNoTarihileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest request);
        
        // CODEGEN: Parameter 'tckimlikNoileiseGirisSorgulaReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileiseGirisSorgula", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/tckimlikNoileiseG" +
            "irisSorgulaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="tckimlikNoileiseGirisSorgulaReturn")]
        ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse tckimlikNoileiseGirisSorgula(ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tckimlikNoileiseGirisSorgula", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/tckimlikNoileiseG" +
            "irisSorgulaResponse")]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse> tckimlikNoileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest request);
        
        // CODEGEN: Parameter 'iseGirisPdfDokumReturn' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisPdfDokum", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/iseGirisPdfDokumR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="iseGirisPdfDokumReturn")]
        ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse iseGirisPdfDokum(ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="iseGirisPdfDokum", ReplyAction="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr/WS_SgkIseGiris/iseGirisPdfDokumR" +
            "esponse")]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse> iseGirisPdfDokumAsync(ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgk4AIseGirisParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private sigortaliIseGiris[] sigortaliIseGirisListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisListesi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public sigortaliIseGiris[] sigortaliIseGirisListesi {
            get {
                return this.sigortaliIseGirisListesiField;
            }
            set {
                this.sigortaliIseGirisListesiField = value;
                this.RaisePropertyChanged("sigortaliIseGirisListesi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class kullaniciBilgileri : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string kullaniciAdiField;
        
        private string isyeriKoduField;
        
        private string sistemSifreField;
        
        private string isyeriSifreField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
                this.RaisePropertyChanged("kullaniciAdi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string isyeriKodu {
            get {
                return this.isyeriKoduField;
            }
            set {
                this.isyeriKoduField = value;
                this.RaisePropertyChanged("isyeriKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string sistemSifre {
            get {
                return this.sistemSifreField;
            }
            set {
                this.sistemSifreField = value;
                this.RaisePropertyChanged("sistemSifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string isyeriSifre {
            get {
                return this.isyeriSifreField;
            }
            set {
                this.isyeriSifreField = value;
                this.RaisePropertyChanged("isyeriSifre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
                this.RaisePropertyChanged("isyeriSicil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class pdfDokumSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hataAciklamaField;
        
        private int hatakoduField;
        
        private byte[] pdfByteArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
                this.RaisePropertyChanged("hatakodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] pdfByteArray {
            get {
                return this.pdfByteArrayField;
            }
            set {
                this.pdfByteArrayField = value;
                this.RaisePropertyChanged("pdfByteArray");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimliktenIseGirisSorParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgkIseGirisKaydi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tckimlikNoField;
        
        private long sicilnoField;
        
        private string girisTarihiField;
        
        private string sigortaTuruField;
        
        private string istisnaKoduField;
        
        private string islemTarihiField;
        
        private double idariParaCezasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
                this.RaisePropertyChanged("tckimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
                this.RaisePropertyChanged("sicilno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string girisTarihi {
            get {
                return this.girisTarihiField;
            }
            set {
                this.girisTarihiField = value;
                this.RaisePropertyChanged("girisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string sigortaTuru {
            get {
                return this.sigortaTuruField;
            }
            set {
                this.sigortaTuruField = value;
                this.RaisePropertyChanged("sigortaTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string istisnaKodu {
            get {
                return this.istisnaKoduField;
            }
            set {
                this.istisnaKoduField = value;
                this.RaisePropertyChanged("istisnaKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
                this.RaisePropertyChanged("islemTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double idariParaCezasi {
            get {
                return this.idariParaCezasiField;
            }
            set {
                this.idariParaCezasiField = value;
                this.RaisePropertyChanged("idariParaCezasi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class iseGirisListesi : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hatakoduField;
        
        private string hataAciklamaField;
        
        private sgkIseGirisKaydi[] iseGirisKayitlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
                this.RaisePropertyChanged("hatakodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
                this.RaisePropertyChanged("hataAciklama");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iseGirisKayitlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sgkIseGirisKaydi[] iseGirisKayitlari {
            get {
                return this.iseGirisKayitlariField;
            }
            set {
                this.iseGirisKayitlariField = value;
                this.RaisePropertyChanged("iseGirisKayitlari");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimlikTarihtenIseGirisSorParametre : object, System.ComponentModel.INotifyPropertyChanged {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        private string iseGirisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
                this.RaisePropertyChanged("kullaniciBilgileri");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string iseGirisTarihi {
            get {
                return this.iseGirisTarihiField;
            }
            set {
                this.iseGirisTarihiField = value;
                this.RaisePropertyChanged("iseGirisTarihi");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisSonuc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long islemSonucuField;
        
        private string islemAciklamasiField;
        
        private long tcKimlikNoField;
        
        private long sicilnoField;
        
        private string adSoyadField;
        
        private long referansKoduField;
        
        private string iseGirisTarihiField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long islemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
                this.RaisePropertyChanged("islemSonucu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string islemAciklamasi {
            get {
                return this.islemAciklamasiField;
            }
            set {
                this.islemAciklamasiField = value;
                this.RaisePropertyChanged("islemAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
                this.RaisePropertyChanged("tcKimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
                this.RaisePropertyChanged("sicilno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string adSoyad {
            get {
                return this.adSoyadField;
            }
            set {
                this.adSoyadField = value;
                this.RaisePropertyChanged("adSoyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public long referansKodu {
            get {
                return this.referansKoduField;
            }
            set {
                this.referansKoduField = value;
                this.RaisePropertyChanged("referansKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string iseGirisTarihi {
            get {
                return this.iseGirisTarihiField;
            }
            set {
                this.iseGirisTarihiField = value;
                this.RaisePropertyChanged("iseGirisTarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
                this.RaisePropertyChanged("isyeriSicil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisIslemSonuclari : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int hataKoduField;
        
        private string hataAciklamasiField;
        
        private sigortaliIseGirisSonuc[] sigortaliIseGirisSonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
                this.RaisePropertyChanged("hataKodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string hataAciklamasi {
            get {
                return this.hataAciklamasiField;
            }
            set {
                this.hataAciklamasiField = value;
                this.RaisePropertyChanged("hataAciklamasi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisSonuc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public sigortaliIseGirisSonuc[] sigortaliIseGirisSonuc {
            get {
                return this.sigortaliIseGirisSonucField;
            }
            set {
                this.sigortaliIseGirisSonucField = value;
                this.RaisePropertyChanged("sigortaliIseGirisSonuc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGiris : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long tckimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string giristarihiField;
        
        private short sigortaliTuruField;
        
        private string gorevkoduField;
        
        private string meslekkoduField;
        
        private string csgbiskoluField;
        
        private string eskihukumluField;
        
        private string ozurluField;
        
        private string ogrenimkoduField;
        
        private string mezuniyetbolumuField;
        
        private short mezuniyetyiliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
                this.RaisePropertyChanged("tckimlikNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
                this.RaisePropertyChanged("ad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
                this.RaisePropertyChanged("soyad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string giristarihi {
            get {
                return this.giristarihiField;
            }
            set {
                this.giristarihiField = value;
                this.RaisePropertyChanged("giristarihi");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short sigortaliTuru {
            get {
                return this.sigortaliTuruField;
            }
            set {
                this.sigortaliTuruField = value;
                this.RaisePropertyChanged("sigortaliTuru");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string gorevkodu {
            get {
                return this.gorevkoduField;
            }
            set {
                this.gorevkoduField = value;
                this.RaisePropertyChanged("gorevkodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string meslekkodu {
            get {
                return this.meslekkoduField;
            }
            set {
                this.meslekkoduField = value;
                this.RaisePropertyChanged("meslekkodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string csgbiskolu {
            get {
                return this.csgbiskoluField;
            }
            set {
                this.csgbiskoluField = value;
                this.RaisePropertyChanged("csgbiskolu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string eskihukumlu {
            get {
                return this.eskihukumluField;
            }
            set {
                this.eskihukumluField = value;
                this.RaisePropertyChanged("eskihukumlu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ozurlu {
            get {
                return this.ozurluField;
            }
            set {
                this.ozurluField = value;
                this.RaisePropertyChanged("ozurlu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string ogrenimkodu {
            get {
                return this.ogrenimkoduField;
            }
            set {
                this.ogrenimkoduField = value;
                this.RaisePropertyChanged("ogrenimkodu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string mezuniyetbolumu {
            get {
                return this.mezuniyetbolumuField;
            }
            set {
                this.mezuniyetbolumuField = value;
                this.RaisePropertyChanged("mezuniyetbolumu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public short mezuniyetyili {
            get {
                return this.mezuniyetyiliField;
            }
            set {
                this.mezuniyetyiliField = value;
                this.RaisePropertyChanged("mezuniyetyili");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisKaydet", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisKaydetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.sgk4AIseGirisParametre sgk4aIseGirisParametre;
        
        public iseGirisKaydetRequest() {
        }
        
        public iseGirisKaydetRequest(ESgk.WorkIn.SgkService.sgk4AIseGirisParametre sgk4aIseGirisParametre) {
            this.sgk4aIseGirisParametre = sgk4aIseGirisParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisKaydetResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisKaydetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.sigortaliIseGirisIslemSonuclari iseGirisKaydetReturn;
        
        public iseGirisKaydetResponse() {
        }
        
        public iseGirisKaydetResponse(ESgk.WorkIn.SgkService.sigortaliIseGirisIslemSonuclari iseGirisKaydetReturn) {
            this.iseGirisKaydetReturn = iseGirisKaydetReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileiseGirisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileiseGirisSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre;
        
        public tckimlikNoTarihileiseGirisSorgulaRequest() {
        }
        
        public tckimlikNoTarihileiseGirisSorgulaRequest(ESgk.WorkIn.SgkService.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre) {
            this.tcKimlikTarihtenIseGirisSorParametre = tcKimlikTarihtenIseGirisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoTarihileiseGirisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoTarihileiseGirisSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoTarihileiseGirisSorgulaReturn;
        
        public tckimlikNoTarihileiseGirisSorgulaResponse() {
        }
        
        public tckimlikNoTarihileiseGirisSorgulaResponse(ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoTarihileiseGirisSorgulaReturn) {
            this.tckimlikNoTarihileiseGirisSorgulaReturn = tckimlikNoTarihileiseGirisSorgulaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileiseGirisSorgula", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileiseGirisSorgulaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre;
        
        public tckimlikNoileiseGirisSorgulaRequest() {
        }
        
        public tckimlikNoileiseGirisSorgulaRequest(ESgk.WorkIn.SgkService.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre) {
            this.tcKimliktenIseGirisSorParametre = tcKimliktenIseGirisSorParametre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tckimlikNoileiseGirisSorgulaResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class tckimlikNoileiseGirisSorgulaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoileiseGirisSorgulaReturn;
        
        public tckimlikNoileiseGirisSorgulaResponse() {
        }
        
        public tckimlikNoileiseGirisSorgulaResponse(ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoileiseGirisSorgulaReturn) {
            this.tckimlikNoileiseGirisSorgulaReturn = tckimlikNoileiseGirisSorgulaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisPdfDokum", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisPdfDokumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.kullaniciBilgileri kullanici;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long referansKodu;
        
        public iseGirisPdfDokumRequest() {
        }
        
        public iseGirisPdfDokumRequest(ESgk.WorkIn.SgkService.kullaniciBilgileri kullanici, long referansKodu) {
            this.kullanici = kullanici;
            this.referansKodu = referansKodu;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="iseGirisPdfDokumResponse", WrapperNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", IsWrapped=true)]
    public partial class iseGirisPdfDokumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESgk.WorkIn.SgkService.pdfDokumSonuc iseGirisPdfDokumReturn;
        
        public iseGirisPdfDokumResponse() {
        }
        
        public iseGirisPdfDokumResponse(ESgk.WorkIn.SgkService.pdfDokumSonuc iseGirisPdfDokumReturn) {
            this.iseGirisPdfDokumReturn = iseGirisPdfDokumReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_SgkIseGirisChannel : ESgk.WorkIn.SgkService.WS_SgkIseGiris, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_SgkIseGirisClient : System.ServiceModel.ClientBase<ESgk.WorkIn.SgkService.WS_SgkIseGiris>, ESgk.WorkIn.SgkService.WS_SgkIseGiris {
        
        public WS_SgkIseGirisClient() {
        }
        
        public WS_SgkIseGirisClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_SgkIseGirisClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SgkIseGirisClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_SgkIseGirisClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESgk.WorkIn.SgkService.iseGirisKaydetResponse ESgk.WorkIn.SgkService.WS_SgkIseGiris.iseGirisKaydet(ESgk.WorkIn.SgkService.iseGirisKaydetRequest request) {
            return base.Channel.iseGirisKaydet(request);
        }
        
        public ESgk.WorkIn.SgkService.sigortaliIseGirisIslemSonuclari iseGirisKaydet(ESgk.WorkIn.SgkService.sgk4AIseGirisParametre sgk4aIseGirisParametre) {
            ESgk.WorkIn.SgkService.iseGirisKaydetRequest inValue = new ESgk.WorkIn.SgkService.iseGirisKaydetRequest();
            inValue.sgk4aIseGirisParametre = sgk4aIseGirisParametre;
            ESgk.WorkIn.SgkService.iseGirisKaydetResponse retVal = ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).iseGirisKaydet(inValue);
            return retVal.iseGirisKaydetReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisKaydetResponse> ESgk.WorkIn.SgkService.WS_SgkIseGiris.iseGirisKaydetAsync(ESgk.WorkIn.SgkService.iseGirisKaydetRequest request) {
            return base.Channel.iseGirisKaydetAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisKaydetResponse> iseGirisKaydetAsync(ESgk.WorkIn.SgkService.sgk4AIseGirisParametre sgk4aIseGirisParametre) {
            ESgk.WorkIn.SgkService.iseGirisKaydetRequest inValue = new ESgk.WorkIn.SgkService.iseGirisKaydetRequest();
            inValue.sgk4aIseGirisParametre = sgk4aIseGirisParametre;
            return ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).iseGirisKaydetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse ESgk.WorkIn.SgkService.WS_SgkIseGiris.tckimlikNoTarihileiseGirisSorgula(ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest request) {
            return base.Channel.tckimlikNoTarihileiseGirisSorgula(request);
        }
        
        public ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoTarihileiseGirisSorgula(ESgk.WorkIn.SgkService.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre) {
            ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest inValue = new ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest();
            inValue.tcKimlikTarihtenIseGirisSorParametre = tcKimlikTarihtenIseGirisSorParametre;
            ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse retVal = ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).tckimlikNoTarihileiseGirisSorgula(inValue);
            return retVal.tckimlikNoTarihileiseGirisSorgulaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse> ESgk.WorkIn.SgkService.WS_SgkIseGiris.tckimlikNoTarihileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest request) {
            return base.Channel.tckimlikNoTarihileiseGirisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaResponse> tckimlikNoTarihileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre) {
            ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest inValue = new ESgk.WorkIn.SgkService.tckimlikNoTarihileiseGirisSorgulaRequest();
            inValue.tcKimlikTarihtenIseGirisSorParametre = tcKimlikTarihtenIseGirisSorParametre;
            return ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).tckimlikNoTarihileiseGirisSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse ESgk.WorkIn.SgkService.WS_SgkIseGiris.tckimlikNoileiseGirisSorgula(ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest request) {
            return base.Channel.tckimlikNoileiseGirisSorgula(request);
        }
        
        public ESgk.WorkIn.SgkService.iseGirisListesi tckimlikNoileiseGirisSorgula(ESgk.WorkIn.SgkService.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre) {
            ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest inValue = new ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest();
            inValue.tcKimliktenIseGirisSorParametre = tcKimliktenIseGirisSorParametre;
            ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse retVal = ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).tckimlikNoileiseGirisSorgula(inValue);
            return retVal.tckimlikNoileiseGirisSorgulaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse> ESgk.WorkIn.SgkService.WS_SgkIseGiris.tckimlikNoileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest request) {
            return base.Channel.tckimlikNoileiseGirisSorgulaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaResponse> tckimlikNoileiseGirisSorgulaAsync(ESgk.WorkIn.SgkService.tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre) {
            ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest inValue = new ESgk.WorkIn.SgkService.tckimlikNoileiseGirisSorgulaRequest();
            inValue.tcKimliktenIseGirisSorParametre = tcKimliktenIseGirisSorParametre;
            return ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).tckimlikNoileiseGirisSorgulaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse ESgk.WorkIn.SgkService.WS_SgkIseGiris.iseGirisPdfDokum(ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest request) {
            return base.Channel.iseGirisPdfDokum(request);
        }
        
        public ESgk.WorkIn.SgkService.pdfDokumSonuc iseGirisPdfDokum(ESgk.WorkIn.SgkService.kullaniciBilgileri kullanici, long referansKodu) {
            ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest inValue = new ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse retVal = ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).iseGirisPdfDokum(inValue);
            return retVal.iseGirisPdfDokumReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse> ESgk.WorkIn.SgkService.WS_SgkIseGiris.iseGirisPdfDokumAsync(ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest request) {
            return base.Channel.iseGirisPdfDokumAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESgk.WorkIn.SgkService.iseGirisPdfDokumResponse> iseGirisPdfDokumAsync(ESgk.WorkIn.SgkService.kullaniciBilgileri kullanici, long referansKodu) {
            ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest inValue = new ESgk.WorkIn.SgkService.iseGirisPdfDokumRequest();
            inValue.kullanici = kullanici;
            inValue.referansKodu = referansKodu;
            return ((ESgk.WorkIn.SgkService.WS_SgkIseGiris)(this)).iseGirisPdfDokumAsync(inValue);
        }
    }
}
