//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ESgk.WorkIn.tr.gov.sgk.sgkt {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_SgkIseGirisPortBinding", Namespace="https://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class WS_SgkIseGirisService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback iseGirisKaydetOperationCompleted;
        
        private System.Threading.SendOrPostCallback tckimlikNoTarihileiseGirisSorgulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback tckimlikNoileiseGirisSorgulaOperationCompleted;
        
        private System.Threading.SendOrPostCallback iseGirisPdfDokumOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_SgkIseGirisService() {
            this.Url = global::ESgk.WorkIn.Properties.Settings.Default.ESgk_WorkIn_tr_gov_sgk_sgkt_WS_SgkIseGirisService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event iseGirisKaydetCompletedEventHandler iseGirisKaydetCompleted;
        
        /// <remarks/>
        public event tckimlikNoTarihileiseGirisSorgulaCompletedEventHandler tckimlikNoTarihileiseGirisSorgulaCompleted;
        
        /// <remarks/>
        public event tckimlikNoileiseGirisSorgulaCompletedEventHandler tckimlikNoileiseGirisSorgulaCompleted;
        
        /// <remarks/>
        public event iseGirisPdfDokumCompletedEventHandler iseGirisPdfDokumCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("iseGirisKaydet", RequestNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ResponseNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("iseGirisKaydetReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sigortaliIseGirisIslemSonuclari iseGirisKaydet([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] sgk4AIseGirisParametre sgk4aIseGirisParametre) {
            object[] results = this.Invoke("iseGirisKaydet", new object[] {
                        sgk4aIseGirisParametre});
            return ((sigortaliIseGirisIslemSonuclari)(results[0]));
        }
        
        /// <remarks/>
        public void iseGirisKaydetAsync(sgk4AIseGirisParametre sgk4aIseGirisParametre) {
            this.iseGirisKaydetAsync(sgk4aIseGirisParametre, null);
        }
        
        /// <remarks/>
        public void iseGirisKaydetAsync(sgk4AIseGirisParametre sgk4aIseGirisParametre, object userState) {
            if ((this.iseGirisKaydetOperationCompleted == null)) {
                this.iseGirisKaydetOperationCompleted = new System.Threading.SendOrPostCallback(this.OniseGirisKaydetOperationCompleted);
            }
            this.InvokeAsync("iseGirisKaydet", new object[] {
                        sgk4aIseGirisParametre}, this.iseGirisKaydetOperationCompleted, userState);
        }
        
        private void OniseGirisKaydetOperationCompleted(object arg) {
            if ((this.iseGirisKaydetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.iseGirisKaydetCompleted(this, new iseGirisKaydetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("tckimlikNoTarihileiseGirisSorgula", RequestNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ResponseNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tckimlikNoTarihileiseGirisSorgulaReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public iseGirisListesi tckimlikNoTarihileiseGirisSorgula([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre) {
            object[] results = this.Invoke("tckimlikNoTarihileiseGirisSorgula", new object[] {
                        tcKimlikTarihtenIseGirisSorParametre});
            return ((iseGirisListesi)(results[0]));
        }
        
        /// <remarks/>
        public void tckimlikNoTarihileiseGirisSorgulaAsync(tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre) {
            this.tckimlikNoTarihileiseGirisSorgulaAsync(tcKimlikTarihtenIseGirisSorParametre, null);
        }
        
        /// <remarks/>
        public void tckimlikNoTarihileiseGirisSorgulaAsync(tcKimlikTarihtenIseGirisSorParametre tcKimlikTarihtenIseGirisSorParametre, object userState) {
            if ((this.tckimlikNoTarihileiseGirisSorgulaOperationCompleted == null)) {
                this.tckimlikNoTarihileiseGirisSorgulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OntckimlikNoTarihileiseGirisSorgulaOperationCompleted);
            }
            this.InvokeAsync("tckimlikNoTarihileiseGirisSorgula", new object[] {
                        tcKimlikTarihtenIseGirisSorParametre}, this.tckimlikNoTarihileiseGirisSorgulaOperationCompleted, userState);
        }
        
        private void OntckimlikNoTarihileiseGirisSorgulaOperationCompleted(object arg) {
            if ((this.tckimlikNoTarihileiseGirisSorgulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tckimlikNoTarihileiseGirisSorgulaCompleted(this, new tckimlikNoTarihileiseGirisSorgulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("tckimlikNoileiseGirisSorgula", RequestNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ResponseNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("tckimlikNoileiseGirisSorgulaReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public iseGirisListesi tckimlikNoileiseGirisSorgula([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre) {
            object[] results = this.Invoke("tckimlikNoileiseGirisSorgula", new object[] {
                        tcKimliktenIseGirisSorParametre});
            return ((iseGirisListesi)(results[0]));
        }
        
        /// <remarks/>
        public void tckimlikNoileiseGirisSorgulaAsync(tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre) {
            this.tckimlikNoileiseGirisSorgulaAsync(tcKimliktenIseGirisSorParametre, null);
        }
        
        /// <remarks/>
        public void tckimlikNoileiseGirisSorgulaAsync(tcKimliktenIseGirisSorParametre tcKimliktenIseGirisSorParametre, object userState) {
            if ((this.tckimlikNoileiseGirisSorgulaOperationCompleted == null)) {
                this.tckimlikNoileiseGirisSorgulaOperationCompleted = new System.Threading.SendOrPostCallback(this.OntckimlikNoileiseGirisSorgulaOperationCompleted);
            }
            this.InvokeAsync("tckimlikNoileiseGirisSorgula", new object[] {
                        tcKimliktenIseGirisSorParametre}, this.tckimlikNoileiseGirisSorgulaOperationCompleted, userState);
        }
        
        private void OntckimlikNoileiseGirisSorgulaOperationCompleted(object arg) {
            if ((this.tckimlikNoileiseGirisSorgulaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tckimlikNoileiseGirisSorgulaCompleted(this, new tckimlikNoileiseGirisSorgulaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("iseGirisPdfDokum", RequestNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", ResponseNamespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("iseGirisPdfDokumReturn", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pdfDokumSonuc iseGirisPdfDokum([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] kullaniciBilgileri kullanici, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long referansKodu) {
            object[] results = this.Invoke("iseGirisPdfDokum", new object[] {
                        kullanici,
                        referansKodu});
            return ((pdfDokumSonuc)(results[0]));
        }
        
        /// <remarks/>
        public void iseGirisPdfDokumAsync(kullaniciBilgileri kullanici, long referansKodu) {
            this.iseGirisPdfDokumAsync(kullanici, referansKodu, null);
        }
        
        /// <remarks/>
        public void iseGirisPdfDokumAsync(kullaniciBilgileri kullanici, long referansKodu, object userState) {
            if ((this.iseGirisPdfDokumOperationCompleted == null)) {
                this.iseGirisPdfDokumOperationCompleted = new System.Threading.SendOrPostCallback(this.OniseGirisPdfDokumOperationCompleted);
            }
            this.InvokeAsync("iseGirisPdfDokum", new object[] {
                        kullanici,
                        referansKodu}, this.iseGirisPdfDokumOperationCompleted, userState);
        }
        
        private void OniseGirisPdfDokumOperationCompleted(object arg) {
            if ((this.iseGirisPdfDokumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.iseGirisPdfDokumCompleted(this, new iseGirisPdfDokumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgk4AIseGirisParametre {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private sigortaliIseGiris[] sigortaliIseGirisListesiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisListesi", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sigortaliIseGiris[] sigortaliIseGirisListesi {
            get {
                return this.sigortaliIseGirisListesiField;
            }
            set {
                this.sigortaliIseGirisListesiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class kullaniciBilgileri {
        
        private string kullaniciAdiField;
        
        private string isyeriKoduField;
        
        private string sistemSifreField;
        
        private string isyeriSifreField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string kullaniciAdi {
            get {
                return this.kullaniciAdiField;
            }
            set {
                this.kullaniciAdiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isyeriKodu {
            get {
                return this.isyeriKoduField;
            }
            set {
                this.isyeriKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sistemSifre {
            get {
                return this.sistemSifreField;
            }
            set {
                this.sistemSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isyeriSifre {
            get {
                return this.isyeriSifreField;
            }
            set {
                this.isyeriSifreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class pdfDokumSonuc {
        
        private string hataAciklamaField;
        
        private int hatakoduField;
        
        private byte[] pdfByteArrayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary")]
        public byte[] pdfByteArray {
            get {
                return this.pdfByteArrayField;
            }
            set {
                this.pdfByteArrayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimliktenIseGirisSorParametre {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sgkIseGirisKaydi {
        
        private long tckimlikNoField;
        
        private long sicilnoField;
        
        private string girisTarihiField;
        
        private string sigortaTuruField;
        
        private string istisnaKoduField;
        
        private string islemTarihiField;
        
        private double idariParaCezasiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string girisTarihi {
            get {
                return this.girisTarihiField;
            }
            set {
                this.girisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sigortaTuru {
            get {
                return this.sigortaTuruField;
            }
            set {
                this.sigortaTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string istisnaKodu {
            get {
                return this.istisnaKoduField;
            }
            set {
                this.istisnaKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string islemTarihi {
            get {
                return this.islemTarihiField;
            }
            set {
                this.islemTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double idariParaCezasi {
            get {
                return this.idariParaCezasiField;
            }
            set {
                this.idariParaCezasiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class iseGirisListesi {
        
        private int hatakoduField;
        
        private string hataAciklamaField;
        
        private sgkIseGirisKaydi[] iseGirisKayitlariField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int hatakodu {
            get {
                return this.hatakoduField;
            }
            set {
                this.hatakoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hataAciklama {
            get {
                return this.hataAciklamaField;
            }
            set {
                this.hataAciklamaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("iseGirisKayitlari", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sgkIseGirisKaydi[] iseGirisKayitlari {
            get {
                return this.iseGirisKayitlariField;
            }
            set {
                this.iseGirisKayitlariField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class tcKimlikTarihtenIseGirisSorParametre {
        
        private kullaniciBilgileri kullaniciBilgileriField;
        
        private long tcKimlikNoField;
        
        private string iseGirisTarihiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public kullaniciBilgileri kullaniciBilgileri {
            get {
                return this.kullaniciBilgileriField;
            }
            set {
                this.kullaniciBilgileriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iseGirisTarihi {
            get {
                return this.iseGirisTarihiField;
            }
            set {
                this.iseGirisTarihiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisSonuc {
        
        private long islemSonucuField;
        
        private string islemAciklamasiField;
        
        private long tcKimlikNoField;
        
        private long sicilnoField;
        
        private string adSoyadField;
        
        private long referansKoduField;
        
        private string iseGirisTarihiField;
        
        private string isyeriSicilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long islemSonucu {
            get {
                return this.islemSonucuField;
            }
            set {
                this.islemSonucuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string islemAciklamasi {
            get {
                return this.islemAciklamasiField;
            }
            set {
                this.islemAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tcKimlikNo {
            get {
                return this.tcKimlikNoField;
            }
            set {
                this.tcKimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long sicilno {
            get {
                return this.sicilnoField;
            }
            set {
                this.sicilnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string adSoyad {
            get {
                return this.adSoyadField;
            }
            set {
                this.adSoyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long referansKodu {
            get {
                return this.referansKoduField;
            }
            set {
                this.referansKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iseGirisTarihi {
            get {
                return this.iseGirisTarihiField;
            }
            set {
                this.iseGirisTarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isyeriSicil {
            get {
                return this.isyeriSicilField;
            }
            set {
                this.isyeriSicilField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGirisIslemSonuclari {
        
        private int hataKoduField;
        
        private string hataAciklamasiField;
        
        private sigortaliIseGirisSonuc[] sigortaliIseGirisSonucField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int hataKodu {
            get {
                return this.hataKoduField;
            }
            set {
                this.hataKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string hataAciklamasi {
            get {
                return this.hataAciklamasiField;
            }
            set {
                this.hataAciklamasiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sigortaliIseGirisSonuc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sigortaliIseGirisSonuc[] sigortaliIseGirisSonuc {
            get {
                return this.sigortaliIseGirisSonucField;
            }
            set {
                this.sigortaliIseGirisSonucField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servisler.ws.tescil4a.isegiris.sgk.gov.tr")]
    public partial class sigortaliIseGiris {
        
        private long tckimlikNoField;
        
        private string adField;
        
        private string soyadField;
        
        private string giristarihiField;
        
        private short sigortaliTuruField;
        
        private string gorevkoduField;
        
        private string meslekkoduField;
        
        private string csgbiskoluField;
        
        private string eskihukumluField;
        
        private string ozurluField;
        
        private string ogrenimkoduField;
        
        private string mezuniyetbolumuField;
        
        private short mezuniyetyiliField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long tckimlikNo {
            get {
                return this.tckimlikNoField;
            }
            set {
                this.tckimlikNoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ad {
            get {
                return this.adField;
            }
            set {
                this.adField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string soyad {
            get {
                return this.soyadField;
            }
            set {
                this.soyadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string giristarihi {
            get {
                return this.giristarihiField;
            }
            set {
                this.giristarihiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short sigortaliTuru {
            get {
                return this.sigortaliTuruField;
            }
            set {
                this.sigortaliTuruField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string gorevkodu {
            get {
                return this.gorevkoduField;
            }
            set {
                this.gorevkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string meslekkodu {
            get {
                return this.meslekkoduField;
            }
            set {
                this.meslekkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string csgbiskolu {
            get {
                return this.csgbiskoluField;
            }
            set {
                this.csgbiskoluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string eskihukumlu {
            get {
                return this.eskihukumluField;
            }
            set {
                this.eskihukumluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ozurlu {
            get {
                return this.ozurluField;
            }
            set {
                this.ozurluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ogrenimkodu {
            get {
                return this.ogrenimkoduField;
            }
            set {
                this.ogrenimkoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mezuniyetbolumu {
            get {
                return this.mezuniyetbolumuField;
            }
            set {
                this.mezuniyetbolumuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short mezuniyetyili {
            get {
                return this.mezuniyetyiliField;
            }
            set {
                this.mezuniyetyiliField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void iseGirisKaydetCompletedEventHandler(object sender, iseGirisKaydetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class iseGirisKaydetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal iseGirisKaydetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sigortaliIseGirisIslemSonuclari Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sigortaliIseGirisIslemSonuclari)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void tckimlikNoTarihileiseGirisSorgulaCompletedEventHandler(object sender, tckimlikNoTarihileiseGirisSorgulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tckimlikNoTarihileiseGirisSorgulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tckimlikNoTarihileiseGirisSorgulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public iseGirisListesi Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((iseGirisListesi)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void tckimlikNoileiseGirisSorgulaCompletedEventHandler(object sender, tckimlikNoileiseGirisSorgulaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tckimlikNoileiseGirisSorgulaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tckimlikNoileiseGirisSorgulaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public iseGirisListesi Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((iseGirisListesi)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void iseGirisPdfDokumCompletedEventHandler(object sender, iseGirisPdfDokumCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class iseGirisPdfDokumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal iseGirisPdfDokumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public pdfDokumSonuc Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((pdfDokumSonuc)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591